#开发环境
server:
  port: 8081

spring:
  datasource:
    username: root
    password: ywhy_7ZS
    url: jdbc:mysql://localhost:3306/springboot-demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

